/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package <%= sourcePackage %>

import kotlin.test.Test
import kotlin.test.assertNotNull

class <%= appClassName %>Test {
    @Test fun appHasAGreeting() {
        val classUnderTest = <%= appClassName %>()
        assertNotNull(classUnderTest.greeting, "<%= appClassName %> should have a greeting")
    }
}
