/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package <%= sourcePackage %>

import kotlin.test.Test
import kotlin.test.assertNotNull

class <%= projectClassName %>Test {
    @Test fun appHasAGreeting() {
        val classUnderTest = <%= projectClassName %>()
        assertNotNull(classUnderTest.greeting, "<%= projectClassName %> should have a greeting")
    }
}
